Traceback (most recent call last):
  File "/data2/liangzilin/anaconda3/envs/Pytorch/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data2/liangzilin/anaconda3/envs/Pytorch/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data2/liangzilin/.vscode-server/extensions/ms-python.python-2024.4.0/python_files/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/data2/liangzilin/.vscode-server/extensions/ms-python.python-2024.4.0/python_files/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/data2/liangzilin/.vscode-server/extensions/ms-python.python-2024.4.0/python_files/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/data2/liangzilin/.vscode-server/extensions/ms-python.python-2024.4.0/python_files/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 322, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/data2/liangzilin/.vscode-server/extensions/ms-python.python-2024.4.0/python_files/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 136, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/data2/liangzilin/.vscode-server/extensions/ms-python.python-2024.4.0/python_files/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/data2/liangzilin/datasets/liangzilin/Knife_code_for_Github/train_OpenBMI.py", line 171, in <module>
  File "/data2/liangzilin/datasets/liangzilin/Knife_code_for_Github/train_OpenBMI.py", line 171, in <listcomp>
    acc_subjects = acc_tmp[0][1]
TypeError: accuracy() missing 2 required positional arguments: 'args' and 'item'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/data2/liangzilin/anaconda3/envs/Pytorch/lib/python3.7/concurrent/futures/process.py", line 99, in _python_exit
  File "/data2/liangzilin/anaconda3/envs/Pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1488752) is killed by signal: Terminated. 
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/data2/liangzilin/anaconda3/envs/Pytorch/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/data2/liangzilin/anaconda3/envs/Pytorch/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1488814) is killed by signal: Terminated. 
